### PR TITLE
check inheritance for abstract DateTimeZone in NodaDateTimeZoneConverter

### PR DESCRIPTION
**Pull request by petriashev**

### CODE REVIEW

**Comment by jskeet** [comment]
Thank you for your pull request. Could you clarify why you've just done this for NodaDateTimeZoneConverter rather than NodaConverterBase? I suspect we could copy the implementation from the Json.NET serializer, and put it in the base class rather than just doing it for a single converter.

**Comment by petriashev** [comment]
DateTimeZone is the only abstract class in NodaTime type system. Other converters works as expected.

**Comment by petriashev** [comment]
In JsonNet implementation there: typeof(T).GetTypeInfo().IsAssignableFrom(objectType.GetTypeInfo())

**Comment by petriashev** [comment]
IsAssignableFrom is more generic. 
Can DateTimeZone have more then one inheritance layers?

**Comment by jskeet** [comment]
> DateTimeZone is the only abstract class in NodaTime type system. Other converters works as expected.

So what *doesn't* work at the moment? You haven't provided any context for what this PR fixes, and as I haven't used System.Text.Json myself I'm somewhat in the dark. Does `JsonConverter<T>` have a default `CanConvert` implementation that's fine for value types and sealed classes, but doesn't work for abstract or other non-sealed classes?

> Can DateTimeZone have more then one inheritance layers?

Potentially, even if it doesn't right now. I wouldn't want the serialization code to be brittle on that account.

**Comment by petriashev** [comment]
> So what _doesn't_ work at the moment? You haven't provided any context for what this PR fixes, and as I haven't used System.Text.Json myself I'm somewhat in the dark. Does `JsonConverter<T>` have a default `CanConvert` implementation that's fine for value types and sealed classes, but doesn't work for abstract or other non-sealed classes?

default JsonConverter<T> has simple check:
```
public override bool CanConvert(Type typeToConvert)
{
    return typeToConvert == typeof(T);
}
```

**Comment by petriashev** [comment]
We can take the same code as in JsonNet base converter

>         // For value types and sealed classes, we can optimize and not call IsAssignableFrom.
>         private static readonly bool CheckAssignableFrom =
>             !(typeof(T).GetTypeInfo().IsValueType || (typeof(T).GetTypeInfo().IsClass && typeof(T).GetTypeInfo().IsSealed));
> 
>         private static readonly Type NullableT = typeof(T).GetTypeInfo().IsValueType 
>             ? typeof(Nullable<>).MakeGenericType(typeof(T)) : typeof(T);
> 
>         // TODO: It's not clear whether we *should* support inheritance here. The Json.NET docs
>         // aren't clear on when this is used - is it for reading or writing? If it's for both, that's
>         // a problem: our "writer" may be okay for subclasses, but that doesn't mean the "reader" is.
>         // This may well only be an issue for DateTimeZone, as everything else uses a sealed type (e.g. Period)
>         // or a value type.
> 
>         /// <summary>
>         /// Returns whether or not this converter supports the given type.
>         /// </summary>
>         /// <param name="objectType">The type to check for compatibility.</param>
>         /// <returns>True if the given type is supported by this converter (including the nullable form for
>         /// value types); false otherwise.</returns>
>         public override bool CanConvert(Type objectType) =>
>             objectType == typeof(T) || objectType == NullableT ||
>             (CheckAssignableFrom && typeof(T).GetTypeInfo().IsAssignableFrom(objectType.GetTypeInfo()));

**Comment by jskeet** [comment]
Sorry for not replying further here - it's still not clear to me whether this is actually fixing a problem, or trying to just improve maintainability.

Can you add a test that fails without the change?

**Comment by petriashev** [comment]
Added test that works only with inheritance support

**Comment by jskeet** [comment]
Thanks - I'll try to take a look over the weekend.

**Comment by petriashev** [comment]
the most lazy PR in my life! )))

**Comment by jskeet** [comment]
Sorry for the delay - I really will try to look over *this* weekend :)

**Review by jskeet — APPROVED** [review]
Thanks - I understand now :)

I think we can probably remove all the GetTypeInfo calls in this repo now, but I'll do that in a separate PR...

**Comment by petriashev** [comment]
> 
> 
> Thanks - I understand now :)
> 
> I think we can probably remove all the GetTypeInfo calls in this repo now, but I'll do that in a separate PR...

I tried to keep code as close as possible to code from NodaTime.Serialization.JsonNet. Thank you!
NodaTime.Serialization.JsonNet

**Pull request merged**
