### PR TITLE
Add converters for AnnualDate for JSON serialization (Json.NET and System.Json.Text)

### LINKED ISSUE #58: Serialization of Nullable<AnnualDate> with System.Text.Json
Using the preview of System.Text.Json serialization, and Asp.Net Core 3.1, I'm getting a default serialization for nullable AnnualDate values when they are not null:

```
{
    "annualDate": {
        "month": 1,
        "day": 1
    },
    "nullableAnnualDateWithValue": {
        "hasValue": true,
        "value": {
            "month": 1,
            "day": 1
        }
    },
    "nullableAnnualDateWithoutValue": null
}
```

This is different to other composite values such as Interval, which serializes as follows:

```
{
    "interval": {
        "start": "1970-01-01T00:00:00Z",
        "end": "1970-01-01T00:00:00Z"
    },
    "nullableIntervalWithValue": {
        "start": "1970-01-01T00:00:00Z",
        "end": "1970-01-01T00:00:00Z"
    },
    "nullableIntervalWithoutValue": null
}
```

Is there any issue preventing the AnnualDate struct being serialized like the others?

### PR DESCRIPTION
**Pull request by dgarciarubio**
Add converter serializing Annual Dates with System.JsonSerialization.
Fixes #58

### CODE REVIEW

**Comment by dgarciarubio** [comment]
I took NodaDateIntervalConverter as an example, as it's very similar in structure. Not sure about the comments though, because English is not my primary language.

**Comment by jskeet** [comment]
Thanks - will review when I get the chance, but it may well not be until late in the weekend.

**Comment by dgarciarubio** [comment]
I didn't think about that, and it makes a lot of sense to have a formatted conversion, after all an annual date is like a local date without the year.

The current implementation for json net serialization is an object though, and I think they should create the same output. Should we change both implementations? Would that be considered a breaking change?

**Comment by jskeet** [comment]
Given that the System.Text.Json package is only in beta, it's fine to make breaking changes. I think it's also reasonable to make the same change in the Json.NET version, to be honest - I don't know whether it would even deserialize properly in its current form anyway.

**Comment by dgarciarubio** [comment]
I was more concerned about the Json.NET package, which is not in beta, but the serialization of the annual date is neither documented nor tested currently, so I guess it wouldn't be an issue to "change" it.

**Pull request merged**
