### PR TITLE
Fix broken nuget link

### PR DESCRIPTION
**Pull request by archanox**

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
Whoops, thanks for this.

**Comment by archanox** [comment]
Sorry about the brevity of the PR message, but I accidentally clicked on that link which lead me to a nasty certificate error which prompted me to send this through.

**Comment by jskeet** [comment]
Not a problem at all. I'm on vacation at the moment, but I'll consider doing a new patch release just to fix the links next weekend.

**Comment by jskeet** [comment]
I've released new versions of all three packages.

**Pull request merged**
